name: check_your_phone
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  all_sensors: ^0.2.1
  earpiece_audio: ^0.0.3
  fullscreen:
  flutter_vibrate: ^1.3.0
  flutter_screenutil: ^5.3.1
  camera:
  audioplayers:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/


  fonts:
    - family: Cairo
      fonts:
        - asset: assets\fonst\Cairo.ttf
